### ISSUE TITLE
ValueError arises in 'posteriors Extended Kalman filter for Premier League football' tutorial + simple fix

### ISSUE THREAD

**Issue by entropich3atdeath** [normal-computing/posteriors#70]
The following ValueError arises in the EKF tutorial - 
_ValueError: Cannot convert from timedelta64[ns] to timedelta64[D]. Supported resolutions are 's', 'ms', 'us', 'ns'._

This is due to the following line in the code to download the data - 
(data["Timestamp"] - origin_date).astype("timedelta64[D]").astype(int)

This is fixed by instead using 
(data["Timestamp"] - origin_date).dt.days.astype(int)

Solution obtained from - https://stackoverflow.com/questions/76363921/how-to-fix-pandas-v2-valueerror-cannot-convert-from-timedelta64ns-to-timedel

**Comment by SamDuffield** [comment]
Looks good! Wanna do a PR? @entropich3atdeath

**Comment by SamDuffield** [comment]
Fixed in #72
