### ISSUE TITLE
Reorganize `utils.py`

### ISSUE THREAD

**Issue by KaelanDt** [normal-computing/posteriors#74]
Right now there is a single utils file, which is fine but will quickly become a mess as we add more functions to it, so better to break it up now. One solution is to just separate it into smaller utils files that go in modules.

**Comment by SamDuffield** [comment]
Splitting to `tree_utils.py` and `utils.py` will already be a lot cleaner

**Comment by SamDuffield** [comment]
Split intro `tree_utils.py` and `utils.py` in #82
