### ISSUE TITLE
Add dense Hessian Laplace

### ISSUE THREAD

**Issue by SamDuffield** [normal-computing/posteriors#99]
Might be worth adding a `laplace.dense_hessian` method since the Hessian is easy to compute with [`torch.func.hessian`](https://pytorch.org/docs/stable/generated/torch.func.hessian.html#torch.func.hessian).

The main problem with this is that the Hessian is not guaranteed to be positive semidefinite, however there may be cases where it is i.e. when we are sure we have optimized exactly to the MAP or simple models. We should add an `epsilon` parameter though that adds a nugget `epsilon * torch.eye(dim)` to the total Hessian that will ensure positive definiteness for `epilson` large enough.

I think we should should **not** add a `laplace.diag_hessian` method since it is [not easy to compute](https://github.com/google/jax/issues/3801#issuecomment-661506518) in contrast to the Fisher methods.

**Comment by jcqcai** [comment]
Hi, Sam. I just wanted to let you know that I have submitted a PR for this: https://github.com/normal-computing/posteriors/pull/112

**Comment by SamDuffield** [comment]
Added in #112 by @jcqcai!
